on:
  workflow_run:
    workflows: [Run and Cache Benchmarks]
    types:
      - completed

name: Track Benchmarks

jobs:
  track_benchmarks:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend: ["postgres", "sqlite", "mysql"]
    env:
      BENCHER_PROJECT: diesel
      BENCHER_ADAPTER: rust_criterion
      BENCHER_TESTBED: ubuntu-latest-${{ matrix.backend }}
      BENCHMARK_RESULTS: ${{ matrix.backend }}.txt
      GITHUB_EVENT: event.json
    steps:
      - name: Download Benchmark Results
        uses: actions/github-script@v6
        with:
          script: |
            async function downloadArtifact(artifactName) {
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id,
              });
              let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name == artifactName
              })[0];
              if (!matchArtifact) {
                core.setFailed(`Failed to find artifact: ${artifactName}`);
              }
              let download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: matchArtifact.id,
                archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${artifactName}.zip`, Buffer.from(download.data));
            }
            await downloadArtifact(process.env.BENCHMARK_RESULTS);
            await downloadArtifact(process.env.GITHUB_EVENT);
      - name: Unzip Benchmark Results
        run: |
          unzip $BENCHMARK_RESULTS.zip
          unzip $GITHUB_EVENT.zip
      - name: Export GitHub Event Data
        uses: actions/github-script@v6
        with:
          script: |
            let fs = require('fs');
            let githubEvent = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT, {encoding: 'utf8'}));
            console.log(githubEvent);
            if (githubEvent.ref) {
              core.exportVariable("EVENT_NAME", "push");
              core.exportVariable("PUSH_REF", githubEvent.ref);
            } else {
              core.exportVariable("EVENT_NAME", "pull_request");
              core.exportVariable("PR_HEAD", githubEvent.pull_request.head.ref);
              core.exportVariable("PR_BASE", githubEvent.pull_request.base.ref);
              core.exportVariable("PR_DEFAULT", githubEvent.pull_request.base.repo.default_branch);
              core.exportVariable("PR_NUMBER", githubEvent.number);
            }
      - uses: bencherdev/bencher@main
      - name: Track Benchmarks
        run: |
          (${{ env.EVENT_NAME == 'push' && env.PUSH_REF == 'refs/heads/master' }} && \
          bencher run \
          --branch "master" \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          --err \
          --file "$BENCHMARK_RESULTS") || \
          (${{ env.EVENT_NAME == 'pull_request'}} && \
          bencher run \
          --if-branch '${{ env.PR_HEAD }}' \
          --else-if-branch '${{ env.PR_BASE }}' \
          --else-if-branch '${{ env.PR_DEFAULT }}' \
          --ci-number '${{ env.PR_NUMBER }}' \
          --github-actions "${{ secrets.GITHUB_TOKEN }}" \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          --err \
          --file "$BENCHMARK_RESULTS")
